---
- name: Add kernel parameter
  become: yes
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    state: present
    reload: yes
  with_items:
    - "net.bridge.bridge-nf-call-ip6tables"
    - "net.bridge.bridge-nf-call-iptables"
    - "net.ipv4.ip_forward"
